# Generated by Django 2.1.3 on 2018-12-26 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerNotification',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='seller',
            name='products',
        ),
        migrations.RemoveField(
            model_name='message',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='messages',
        ),
        migrations.AddField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='Id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default='message', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='draft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='fullname',
            field=models.CharField(default='nothing', max_length=30),
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='sendto',
            field=models.CharField(blank=True, default=shop.models.get_superuser_email, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, default='Contact Us', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='date_seller',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_seller',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.CharField(default='nothing', max_length=30),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.AddField(
            model_name='sellernotification',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Profile'),
        ),
    ]
