# Generated by Django 2.1.3 on 2018-12-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20181226_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_seller',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
