# Generated by Django 2.1.3 on 2018-12-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20181226_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_seller',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
