# Generated by Django 2.1.3 on 2019-01-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20181226_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featues',
            new_name='features',
        ),
    ]
